### ISSUE TITLE
How to achieve substitution in tests with mocks if interface references cannot be injected?

### ISSUE THREAD

**Issue by orospakr** [facebookgo/inject#4]
Like so many others before, I'd like to leverage the benefits of DI by using the same references on a struct I'm testing for manually set mock/stub structs in addition to having Inject populate them at normal runtime.

However, in Golang, there's no Liskov-style substitution unless you're using interfaces.  The Inject doc mentions that "supports injection for interface types as long as they’re unambiguous", but I'm not sure what is meant there or if it's even relevant to this problem.

I'd rather avoid having to manually create all such substitutable structs, because that means I'd have to create all such things at the top level, partially negating the value of using Inject (having a highly-polluted main()).

Perhaps an extra parameter to the `inject` tag to indicate which object should be constructed to satisfy the interface requirement by default?

**Comment by daaku** [comment]
Construction of non-concrete objects is not something inject supports. This has worked well for us, and our `main()`s are not sufficiently large yet to be of concern. I'm not entirely sure how an extra parameter to the `inject` tag would work either since it's essentially impossible to go from a string to a concrete implementation/constructor without also having another mapping table somewhere, at which point the current approach of `main()` having a list of concrete implementations seems comparable anyways.

**Comment by orospakr** [comment]
Ah well, I figured it was worth asking!  Thank you :)
